# ============================================================
# VM MAC addresses
# ============================================================
#
# Use these to configure DHCP reservations (MAC → IP) in your router.
# This ensures each VM always boots with the IP you defined in your variables,
# so that Terraform can reach the Talos API at the expected address.

output "control_plane_mac_addresses" {
  description = "MAC addresses of control plane VMs. Use these for DHCP reservations."
  value = {
    for name, vm in module.control_plane_vms : name => vm.mac_address
  }
}

output "worker_mac_addresses" {
  description = "MAC addresses of worker VMs. Use these for DHCP reservations."
  value = {
    for name, vm in module.worker_vms : name => vm.mac_address
  }
}

# ============================================================
# Cluster access
# ============================================================

output "kubeconfig_path" {
  description = "Path to the generated kubeconfig file (created after 'terraform apply' completes)"
  value       = "${path.module}/kubeconfig"
}

output "talosconfig_path" {
  description = "Path to the talosconfig file generated by talhelper (use with talosctl --talosconfig)"
  value       = "${path.module}/clusterconfig/talosconfig"
}
